### ISSUE TITLE
Undefined constant PDO::MYSQL_ATTR_INIT_COMMAND in /home/yann/Documents/sources/NuitInfo2022/src/Repository/DatabaseConnection.php:17

### ISSUE THREAD

**Issue by WoodenMaiden** [Lunalaaaa/NuitInfo2022#1]
# Steps to reproduce

- clone the repo locally
- ``php -S http://localhost:8000``
- access http://localhost:8000

IS this normal that ``PDO`` does not have said attribute ? is this a library ?

**Comment by pontatot** [comment]
Hello
[PDO](https://www.php.net/manual/en/intro.pdo.php) is indeed a library shipped with PHP
The said constant is from the [PDO_MYSQL driver](https://www.php.net/manual/en/ref.pdo-mysql.php#pdo.constants.mysql-attr-init-command) and is currently implemented in the PDO interface
It should therefore be available
